# Generated by Django 5.2.12 on 2026-04-05 00:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chargers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('energy_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='chargers.charger')),
            ],
            options={
                'db_table': 'charging_sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
