# Generated by Django 5.2.12 on 2026-04-05 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charging_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chargingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_id__isnull', False)), fields=('transaction_id',), name='unique_transaction_id'),
        ),
    ]
